### ISSUE TITLE
ActionView::Template::Error: undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by jsyeo** [Coursemology/coursemology.org#390] opened 2015-01-27 16:36 UTC
View details in Rollbar: [https://rollbar.com/jsyeo/coursemology.org/items/58/](https://rollbar.com/jsyeo/coursemology.org/items/58/)

```

NoMethodError: undefined method `name' for nil:NilClass
  File "/home/raymoond/jenkins/workspace/coursemology_second/app/views/assessment/mission_submissions/_scribing_canvas.html.erb", line 11, in block in _app_views_assessment_mission_submissions__scribing_canvas_html_erb___1586345478826584770_81658540
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.14/lib/active_record/associations/collection_proxy.rb", line 89, in each
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.14/lib/active_record/associations/collection_proxy.rb", line 89, in method_missing
  File "/home/raymoond/jenkins/workspace/coursemology_second/app/views/assessment/mission_submissions/_scribing_canvas.html.erb", line 4, in _app_views_assessment_mission_submissions__scribing_canvas_html_erb___1586345478826584770_81658540
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/template.rb", line 145, in block in render
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.14/lib/active_support/notifications.rb", line 125, in instrument
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/template.rb", line 143, in render
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/renderer/partial_renderer.rb", line 265, in render_partial
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/renderer/partial_renderer.rb", line 238, in block in render
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/renderer/abstract_renderer.rb", line 38, in block in instrument
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.14/lib/active_support/notifications.rb", line 123, in block in instrument
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb", line 20, in instrument
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.14/lib/active_support/notifications.rb", line 123, in instrument
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/renderer/abstract_renderer.rb", line 38, in instrument
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/rails3/action_controller.rb", line 177, in block in instrument_with_newrelic
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/method_tracer.rb", line 219, in trace_execution_scoped
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/rails3/action_controller.rb", line 176, in instrument_with_newrelic
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/renderer/partial_renderer.rb", line 237, in render
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/renderer/renderer.rb", line 41, in render_partial
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/renderer/renderer.rb", line 15, in render
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/helpers/rendering_helper.rb", line 24, in render
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/haml-4.0.5/lib/haml/helpers/action_view_mods.rb", line 12, in render_with_haml
  File "/home/raymoond/jenkins/workspace/coursemology_second/app/views/assessment/gradings/_single_question_form.html.erb", line 25, in block in _app_views_assessment_gradings__single_question_form_html_erb___1441966275545842651_81970440
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/helpers/capture_helper.rb", line 40, in block in capture
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/helpers/capture_helper.rb", line 187, in with_output_buffer
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/haml-4.0.5/lib/haml/helpers/action_view_xss_mods.rb", line 5, in with_output_buffer_with_haml_xss
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/helpers/capture_helper.rb", line 40, in capture
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/haml-4.0.5/lib/haml/helpers/action_view_mods.rb", line 52, in capture_with_haml
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/helpers/form_helper.rb", line 378, in form_for
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/haml-4.0.5/lib/haml/helpers/action_view_mods.rb", line 139, in form_for_with_haml
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/haml-4.0.5/lib/haml/helpers/action_view_xss_mods.rb", line 28, in form_for_with_haml_xss
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/bundler/gems/simple_form-a43bd2722f95/lib/simple_form/action_view_extensions/form_helper.rb", line 29, in block in simple_form_for
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/bundler/gems/simple_form-a43bd2722f95/lib/simple_form/action_view_extensions/form_helper.rb", line 48, in with_simple_form_field_error_proc
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/bundler/gems/simple_form-a43bd2722f95/lib/simple_form/action_view_extensions/form_helper.rb", line 28, in simple_form_for
  File "/home/raymoond/jenkins/workspace/coursemology_second/app/views/assessment/gradings/_single_question_form.html.erb", line 3, in _app_views_assessment_gradings__single_question_form_html_erb___1441966275545842651_81970440
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/template.rb", line 145, in block in render
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.14/lib/active_support/notifications.rb", line 125, in instrument
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/template.rb", line 143, in render
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/renderer/partial_renderer.rb", line 265, in render_partial
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/renderer/partial_renderer.rb", line 238, in block in render
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/renderer/abstract_renderer.rb", line 38, in block in instrument
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.14/lib/active_support/notifications.rb", line 123, in block in instrument
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb", line 20, in instrument
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.14/lib/active_support/notifications.rb", line 123, in instrument
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.14/lib/action_view/renderer/abstract_renderer.rb", line 38, in instrument
  File "/home/raymoond/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-

**Comment by jsyeo** [comment] 2015-01-27 16:55
@kxmbrian I'm getting this exception whenever I refresh the page after scribing.

**Comment by wangqiang1208** [comment] 2015-01-28 01:11
Hmm, I think the grading view has some problem, I don't see the exception
but I see a lot of raw data, and I cannot save gradings.

Sorry,I didn't test grading also ><

**Comment by kxmbrian** [comment] 2015-01-28 14:07
@wangqiang1208 do you have a screenshot? This should have been fixed in the PR.

**Comment by wangqiang1208** [comment] 2015-01-28 14:32
Oh, sorry, I think I"m not using your latest code this morning.

And when I use the latest code, also cannot reproduce Jason's exception .

**Comment by wangqiang1208** [comment] 2015-01-28 15:18
@kxmbrian My debugging shows that this answer has 3 scribbles, and 2 of them have a nil std_course_id.

**Closed** 2015-07-03 08:27 UTC
Labels: error
